services:
  app:
    build:
      context: .
      dockerfile: .Dockerfile
    ports:
      - "80:80"
    links:
      - db
    networks:
      - app_network

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=golang_boilerplate
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
