services:
  app:
    build:
      context: .
      dockerfile: .Dockerfile
    ports:
      - "80:80"
    links:
      - db
    networks:
      - app_network
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=golang_boilerplate
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
    networks:
      - app_network
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 1s
      interval: 1s
      timeout: 5s
      retries: 55

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
